yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% load static %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">
    <h1>Привет, я автор этого проекта</h1>
  
      <p>
        Начинающий backend developer
      </p>
      <p>
        И если вы читаете эту страницу, значит что-то на созданном мною сайте работает )) 
      </p>
      <p>
        И это здорово, потому что как и всем известный путь в тысячи ли, большой проект начинается с первых простых страниц.
      </p>
      <p>
        Программирование это очень круто! Каждый программист по сути маленький бог, творец в рамках своего отдельно взятого task-а.<br> 
        Он создает сущности, которые начинают жить, общаться друг с другом и трудиться в соответствии с разработанным алгоритмом.
      <p>
        При этом надо быть очень внимательным ко всем созданиям, не пропускать скобочки, считать отступы,<br>
        иначе все начинает рушиться и никто не хочет работать.
      </p>
      <p>
        А сколько всякого <a href="{% url "about:tech" %}">инструментария</a> для творцов было придумано, а сколько еще будет... Во всем этом очень трудно разобраться,<br>
        но ВОЗМОЖНО... для тех, кто хочет создавать красивые и полезные миры.
      </p>
      <p>  
        Так что если заметите поссорившиеся сущности или отлынивающие от работы объекты на этом проекте, <br>
        пишите начинающему божеству на адрес <a href="mailto:mtaurova@yandex.ru">mtaurova@yandex.ru</a>.
        Будем исправляться
      </p> 

      <img src="{% static 'img/about.png' %}" width="540" height="360" class="d-inline-block align-top" alt="">
       
  </div>  
</div>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <h1>Технологии:</h1>        
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Python
          </li>
          <li class="list-group-item">
            Django
          </li>
          <li class="list-group-item">
            Pillow
          </li> 
          <li class="list-group-item">
            Sorl-thumbnail
          </li>
          <li class="list-group-item">
            Bootstrap
          </li>         
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <div class="text-center py-3">
          <h3>Основная технология - "Не сдаваться 3.0"</h3>
        </div>
      </article>
  </div>
</div>
{% endblock %} 