yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

handler404 = 'core.views.page_not_found'


urlpatterns = [
    path('', views.index, name='home'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('group/<slug:slug>/', views.goup_posts, name='group_posts'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'
         ),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'
         ),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    description = models.TextField()
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='группа',
        help_text='Группа поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(
        verbose_name='текст',
        help_text='Напишите свой пост здесь'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )

    class Meta:
        verbose_name = 'подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='followed'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст комментария'}
        help_texts = {'text': 'Напишите свой комментарий здесь'}


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'image': 'Картинка',
            'group': 'Группа',
            'text': 'Текст поста'
        }
        help_texts = {
            'image': 'Загрузите изображение',
            'group': 'Выберите нужную группу из списка',
            'text': 'Напишите свой пост здесь'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import get_pages


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    post = Post.objects.filter(author__following__user=request.user)
    context = get_pages(post, request)
    return render(request, template, context)


def goup_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(get_pages(group.posts.all(), request))
    return render(request, template, context)


def index(request):
    template = 'posts/index.html'
    context = get_pages(Post.objects.all(), request)
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    return render(request, template, {"form": form})


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    post_count = post.author.posts.count()
    context = {
        'post': post,
        'form': form,
        'post_count': post_count,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_count = author.posts.count()
    is_following = author.following.filter(
        user_id=request.user.id).exists()
    context = {
        'author': author,
        'post_count': post_count,
        'is_following': is_following,
    }
    context.update(get_pages(author.posts.all(), request))
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    if username != request.user.username:
        author = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
{% load thumbnail %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          Редактировать запись
          {% else %}
          Новый пост
          {% endif %}
        </div>
        <div class="card-body">

          <form method="post" enctype="multipart/form-data"> 
          
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>    
              {{ field|addclass:"form-control" }}

              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
              
            </div>
          {% endfor %}

            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    {% include 'includes/switcher.html' %}     
    <h1>Ваши избранные авторы</h1>
    {% load cache %}
    {% cache 20 index_page %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">все посты автора</a><br>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>

        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}

        <p>{{ post.text }}</p>

        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>

        {% if post.group %}     
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}

        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Посты группы {{ group.title }}
{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h1> {{ group.title }}</h1>
      <p>{{ group.description }}</p>

        {% for post in  page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты автора</a><br>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>

          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}

          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>    
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          
          {% if not forloop.last %}<hr>{% endif %}   
        {% endfor %}

        {% include 'includes/paginator.html' %}
  </div>       
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Главная страница
{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5"> 
    {% include 'includes/switcher.html' %}    
    <h1>Последние обновления на сайте</h1>

    {% load cache %}
    {% cache 20 index_page with page_obj %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">все посты автора</a><br>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>

        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}

        <p>{{ post.text }}</p>

        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
        {% if post.group %}     
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
             
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% endcache %}

    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>

            {% if post.group %}   
            <li class="list-group-item"> 
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}

            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>

          </ul>
        </aside>

        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}

          <p>
            {{ post.text }}
          </p>          
          <p>
            {% if user.username == post.author.username %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
                редактировать запись
            </a>
            {% endif %}
          </p>
          <p>
            <div class="row">
              {% if user.is_authenticated %}
                <div class="card my-4">
                  <h5 class="card-header">Добавить комментарий:</h5>
                  <div class="card-body">
                    <form method="post" action="{% url 'posts:add_comment' post.id %}">
                      {% csrf_token %}      
                      <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                      </div>
                      <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                  </div>
                </div>
              {% endif %}
    
              {% for comment in comments %}
                <div class="media mb-4">
                  <div class="media-body">
                    <h5 class="mt-0">
                      <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                      </a>
                    </h5>
                    <p>
                      {{ comment.text }}
                    </p>
                  </div>
                </div>
              {% endfor %}
               
            </div>
          </p> 
        </article>
        
      </div>
    </div> 
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
 Профайл {{ author }}
{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author }} </h1>
      <p>Всего постов: {{ post_count }} </p>
      {% if user.username != author.username %}
        {% if is_following %} 
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ author }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
            {% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
        {% include 'includes/paginator.html' %}
  </div>
{% endblock %}